CREATE TABLE IF NOT EXISTS contents (
    id CHAR(26) NOT NULL PRIMARY KEY,
    content LONGTEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
