const BASE_URL = "http://localhost:3000";

async function seed() {
  console.log("Seeding 10 posts...");
  for (let i = 1; i <= 10; i++) {
    const content = `# Post ${i}

This is the **${i}th** post content generated by the seed script.

## Features
- Markdown support
- List items:
  - Item A
  - Item B

> "AI-generated content is the future."
`;

    try {
      const res = await fetch(`${BASE_URL}/api/contents`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });

      if (res.ok) {
        const data = await res.json();
        console.log(`Created post ${i}: ${data.id}`);
      } else {
        console.error(
          `Failed to create post ${i}: ${res.status} ${res.statusText}`,
        );
      }
    } catch (e) {
      console.error(
        `Error connecting to ${BASE_URL}. Make sure the server is running!`,
      );
      console.error(e);
      process.exit(1);
    }
  }
  console.log("Seeding complete.");
}

seed();
